<optgroup label="United States">
  <option value="AL" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='AL'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='AL'? 'selected="selected"' : '' ); } ?>>Alabama</option>
  <option value="AK" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='AK'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='AK'? 'selected="selected"' : '' ); } ?>>Alaska</option>
  <option value="AZ" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='AZ'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='AZ'? 'selected="selected"' : '' ); } ?>>Arizona</option>
  <option value="AR" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='AR'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='AR'? 'selected="selected"' : '' ); } ?>>Arkansas</option>
  <option value="CA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='CA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='CA'? 'selected="selected"' : '' ); } ?>>California</option>
  <option value="CO" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='CO'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='CO'? 'selected="selected"' : '' ); } ?>>Colorado</option>
  <option value="CT" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='CT'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='CT'? 'selected="selected"' : '' ); } ?>>Connecticut</option>
  <option value="DE" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='DE'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='DE'? 'selected="selected"' : '' ); } ?>>Delaware</option>
  <option value="DC" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='DC'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='DC'? 'selected="selected"' : '' ); } ?>>District Of Columbia</option>
  <option value="FL" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='FL'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='FL'? 'selected="selected"' : '' ); } ?>>Florida</option>
  <option value="GA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='GA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='GA'? 'selected="selected"' : '' ); } ?>>Georgia</option>
  <option value="HI" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='HI'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='HI'? 'selected="selected"' : '' ); } ?>>Hawaii</option>
  <option value="ID" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='ID'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='ID'? 'selected="selected"' : '' ); } ?>>Idaho</option>
  <option value="IL" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='IL'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='IL'? 'selected="selected"' : '' ); } ?>>Illinois</option>
  <option value="IN" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='IN'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='IN'? 'selected="selected"' : '' ); } ?>>Indiana</option>
  <option value="IA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='IA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='IA'? 'selected="selected"' : '' ); } ?>>Iowa</option>
  <option value="KS" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='KS'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='KS'? 'selected="selected"' : '' ); } ?>>Kansas</option>
  <option value="KY" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='KY'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='KY'? 'selected="selected"' : '' ); } ?>>Kentucky</option>
  <option value="LA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='LA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='LA'? 'selected="selected"' : '' ); } ?>>Louisiana</option>
  <option value="ME" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='ME'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='ME'? 'selected="selected"' : '' ); } ?>>Maine</option>
  <option value="MD" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MD'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MD'? 'selected="selected"' : '' ); } ?>>Maryland</option>
  <option value="MA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MA'? 'selected="selected"' : '' ); } ?>>Massachusetts</option>
  <option value="MI" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MI'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MI'? 'selected="selected"' : '' ); } ?>>Michigan</option>
  <option value="MN" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MN'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MS'? 'selected="selected"' : '' ); } ?>>Minnesota</option>
  <option value="MS" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MS'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MN'? 'selected="selected"' : '' ); } ?>>Mississippi</option>
  <option value="MO" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MO'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MO'? 'selected="selected"' : '' ); } ?>>Missouri</option>
  <option value="MT" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MT'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MT'? 'selected="selected"' : '' ); } ?>>Montana</option>
  <option value="NE" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NE'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NE'? 'selected="selected"' : '' ); } ?>>Nebraska</option>
  <option value="NV" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NV'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NV'? 'selected="selected"' : '' ); } ?>>Nevada</option>
  <option value="NH" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NH'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NH'? 'selected="selected"' : '' ); } ?>>New Hampshire</option>
  <option value="NJ" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NJ'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NJ'? 'selected="selected"' : '' ); } ?>>New Jersey</option>
  <option value="NM" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NM'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NM'? 'selected="selected"' : '' ); } ?>>New Mexico</option>
  <option value="NY" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NY'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NY'? 'selected="selected"' : '' ); } ?>>New York</option>
  <option value="NC" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NC'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NC'? 'selected="selected"' : '' ); } ?>>North Carolina</option>
  <option value="ND" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='ND'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='ND'? 'selected="selected"' : '' ); } ?>>North Dakota</option>
  <option value="OH" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='OH'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='OH'? 'selected="selected"' : '' ); } ?>>Ohio</option>
  <option value="OK" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='OK'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='OK'? 'selected="selected"' : '' ); } ?>>Oklahoma</option>
  <option value="OR" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='OR'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='OR'? 'selected="selected"' : '' ); } ?>>Oregon</option>
  <option value="PA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='PA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='PA'? 'selected="selected"' : '' ); } ?>>Pennsylvania</option>
  <option value="RI" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='RI'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='RI'? 'selected="selected"' : '' ); } ?>>Rhode Island</option>
  <option value="SC" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='SC'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='SC'? 'selected="selected"' : '' ); } ?>>South Carolina</option>
  <option value="SD" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='SD'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='SD'? 'selected="selected"' : '' ); } ?>>South Dakota</option>
  <option value="TN" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='TN'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='TN'? 'selected="selected"' : '' ); } ?>>Tennessee</option>
  <option value="TX" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='TX'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='TX'? 'selected="selected"' : '' ); } ?>>Texas</option>
  <option value="UT" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='UT'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='UT'? 'selected="selected"' : '' ); } ?>>Utah</option>
  <option value="VT" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='VT'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='VT'? 'selected="selected"' : '' ); } ?>>Vermont</option>
  <option value="VA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='VA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='VA'? 'selected="selected"' : '' ); } ?>>Virginia</option>
  <option value="WA" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='WA'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='WA'? 'selected="selected"' : '' ); } ?>>Washington</option>
  <option value="WV" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='WV'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='WV'? 'selected="selected"' : '' ); } ?>>West Virginia</option>
  <option value="WI" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='WI'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='WI'? 'selected="selected"' : '' ); } ?>>Wisconsin</option>
  <option value="WY" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='WY'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='WY'? 'selected="selected"' : '' ); } ?>>Wyoming</option>
</optgroup>
<optgroup label="Canada">
  <option value="AB" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='AB'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='AB'? 'selected="selected"' : '' ); } ?>>Alberta</option>
  <option value="BC" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='BC'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='BC'? 'selected="selected"' : '' ); } ?>>British Columbia</option>
  <option value="MB" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='MB'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='MB'? 'selected="selected"' : '' ); } ?>>Manitoba</option>
  <option value="NB" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NB'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NB'? 'selected="selected"' : '' ); } ?>>New Brunswick</option>
  <option value="NL" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NL'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NL'? 'selected="selected"' : '' ); } ?>>Newfoundland and Labrador</option>
  <option value="NS" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NS'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NS'? 'selected="selected"' : '' ); } ?>>Nova Scotia</option>
  <option value="ON" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='ON'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='ON'? 'selected="selected"' : '' ); } ?>>Ontario</option>
  <option value="PE" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='PE'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='PE'? 'selected="selected"' : '' ); } ?>>Prince Edward Island</option>
  <option value="QC" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='QC'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='QC'? 'selected="selected"' : '' ); } ?>>Quebec</option>
  <option value="SK" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='SK'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='SK'? 'selected="selected"' : '' ); } ?>>Saskatchewan</option>
  <option value="NT" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NT'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NT'? 'selected="selected"' : '' ); } ?>>Northwest Territories</option>
  <option value="NU" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='NU'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='NU'? 'selected="selected"' : '' ); } ?>>Nunavut</option>
  <option value="YT" <?php if (empty($_SESSION["florist-one-flower-delivery-recipient-address-state"]) && $autopop == 1){ echo ($config_options['address_state']=='YT'? 'selected="selected"' : '' ); } else { echo ($_SESSION['florist-one-flower-delivery-recipient-state']=='YT'? 'selected="selected"' : '' ); } ?>>Yukon</option>
</optgroup>
